/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.CtrlPrincipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author wquentel
 */
public class VueMenu extends javax.swing.JFrame {

    private VueMenu vueMenu = this;

    /**
     * Creates new form VueMenu1
     */
    public VueMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jBoutonBilleterie = new javax.swing.JButton();
        jBoutonRepresentation = new javax.swing.JButton();
        jButtonDeconnection = new javax.swing.JButton();
        jRadioButtonLocale = new javax.swing.JRadioButton();
        jRadioButtonDistance = new javax.swing.JRadioButton();
        jButtonSynchronisation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Menu Festival");

        jBoutonBilleterie.setText("Billeterie");

        jBoutonRepresentation.setText("Représentation");
        jBoutonRepresentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoutonRepresentationActionPerformed(evt);
            }
        });

        jButtonDeconnection.setText("Déconnection");

        buttonGroup1.add(jRadioButtonLocale);
        jRadioButtonLocale.setText("Locale");
        jRadioButtonLocale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLocaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDistance);
        jRadioButtonDistance.setText("Distante");

        jButtonSynchronisation.setText("Synchronisation");
        jButtonSynchronisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSynchronisationActionPerformed(evt);
            }
        });

        jLabel2.setText("Local to Distant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBoutonBilleterie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBoutonRepresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButtonDistance)
                            .addGap(0, 0, 0)
                            .addComponent(jRadioButtonLocale))
                        .addComponent(jButtonDeconnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(30, 30, 30))
                        .addComponent(jButtonSynchronisation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jBoutonBilleterie)
                .addGap(6, 6, 6)
                .addComponent(jBoutonRepresentation)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDistance)
                    .addComponent(jRadioButtonLocale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSynchronisation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeconnection)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBoutonRepresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoutonRepresentationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoutonRepresentationActionPerformed

    private void jRadioButtonLocaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLocaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLocaleActionPerformed

    private void jButtonSynchronisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSynchronisationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSynchronisationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueMenu().setVisible(true);
            }
        });
        
    }

    public JButton getjBoutonBilleterie() {
        return jBoutonBilleterie;
    }

    public JButton getjBoutonRepresentation() {
        return jBoutonRepresentation;
    }

    public JButton getjButtonDeconnection() {
        return jButtonDeconnection;
    }
    public JRadioButton getjRadioButtonDistance() {
        return jRadioButtonDistance;
    }

    public JRadioButton getjRadioButtonLocale() {
        return jRadioButtonLocale;
    }
    public void setJRationButtonLocale(){
        this.jRadioButtonLocale.setSelected(true);
    }
    public JButton getJButtonSynchronisation(){
        return jButtonSynchronisation;
    }
    public void setJButtonSynchronisation(){
        this.jButtonSynchronisation.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBoutonBilleterie;
    private javax.swing.JButton jBoutonRepresentation;
    private javax.swing.JButton jButtonDeconnection;
    private javax.swing.JButton jButtonSynchronisation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonDistance;
    private javax.swing.JRadioButton jRadioButtonLocale;
    // End of variables declaration//GEN-END:variables

    
}
